import { MigrationInterface, QueryRunner } from "typeorm";

export class CamiadoIdEntidades1703699308257 implements MigrationInterface {
    name = 'CamiadoIdEntidades1703699308257'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "mod_auth"."log_history" ("id" BIGSERIAL NOT NULL, "date" TIMESTAMP DEFAULT now(), "model" character varying NOT NULL, "data" jsonb, "action" character varying NOT NULL, "record" integer, "user_id" bigint, CONSTRAINT "PK_837ee3d001208e2b7400e7a0487" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP CONSTRAINT "UQ_d34106f8ec1ebaf66f4f8609dd6"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "user_name"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "refresh_token_exp"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "userName" character varying(25) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD CONSTRAINT "UQ_da5934070b5f2726ebfd3122c80" UNIQUE ("userName")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "refreshtoken" character varying`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "refreshtokenexp" date`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "FK_074ceeadf723390b0fb9f582a5d"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "FK_46dc4d18f715459d7bf682d32b9"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "FK_dd96b3b407b3a5c35195993c16a"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "FK_e959bd66b9f5a8c77de4fd589eb"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" DROP CONSTRAINT "PK_c93a22388638fac311781c7f2dd"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" ADD CONSTRAINT "PK_c93a22388638fac311781c7f2dd" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP CONSTRAINT "FK_081bb94cc56736d4d76a6e66d98"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_237a0fe43278378e9c5729d17af"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "PK_35b2a8f47d153ff7a41860cceeb"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "PK_35b2a8f47d153ff7a41860cceeb" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "menu_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "menu_id" bigint`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "FK_171ab157447420f1284a8a45d65"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "FK_273f59cc606dc3d818235f08796"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP CONSTRAINT "FK_8d632ce50f972ad8f58ea565c74"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP CONSTRAINT "PK_048102c1546244e94f6dab37f45"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD CONSTRAINT "PK_048102c1546244e94f6dab37f45" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP CONSTRAINT "REL_081bb94cc56736d4d76a6e66d9"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP COLUMN "menu_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD "menu_id" bigint`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD CONSTRAINT "UQ_081bb94cc56736d4d76a6e66d98" UNIQUE ("menu_id")`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."provincia" ALTER COLUMN "geom" TYPE geometry`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."provincia" ALTER COLUMN "centroide" TYPE geometry`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."municipio" ALTER COLUMN "geom" TYPE geometry`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."municipio" ALTER COLUMN "centroide" TYPE geometry`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_7cf100d94c639983ce7a545526f"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_e959bd66b9f5a8c77de4fd589eb" PRIMARY KEY ("rol_id")`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_46dc4d18f715459d7bf682d32b"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD "user_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_e959bd66b9f5a8c77de4fd589eb"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_7cf100d94c639983ce7a545526f" PRIMARY KEY ("rol_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_7cf100d94c639983ce7a545526f"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_46dc4d18f715459d7bf682d32b9" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_e959bd66b9f5a8c77de4fd589e"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP COLUMN "rol_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD "rol_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_46dc4d18f715459d7bf682d32b9"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_7cf100d94c639983ce7a545526f" PRIMARY KEY ("user_id", "rol_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_fe11cc91f4d6799b60d91973857"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_171ab157447420f1284a8a45d65" PRIMARY KEY ("funcion_id")`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_074ceeadf723390b0fb9f582a5"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD "user_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_171ab157447420f1284a8a45d65"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_fe11cc91f4d6799b60d91973857" PRIMARY KEY ("funcion_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_fe11cc91f4d6799b60d91973857"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_074ceeadf723390b0fb9f582a5d" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_171ab157447420f1284a8a45d6"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP COLUMN "funcion_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD "funcion_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_074ceeadf723390b0fb9f582a5d"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_fe11cc91f4d6799b60d91973857" PRIMARY KEY ("user_id", "funcion_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_52aa46684e8437845bb0ac020cd"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_273f59cc606dc3d818235f08796" PRIMARY KEY ("funcion_id")`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_dd96b3b407b3a5c35195993c16"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP COLUMN "rol_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD "rol_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_273f59cc606dc3d818235f08796"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_52aa46684e8437845bb0ac020cd" PRIMARY KEY ("funcion_id", "rol_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_52aa46684e8437845bb0ac020cd"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_dd96b3b407b3a5c35195993c16a" PRIMARY KEY ("rol_id")`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_273f59cc606dc3d818235f0879"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP COLUMN "funcion_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD "funcion_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_dd96b3b407b3a5c35195993c16a"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_52aa46684e8437845bb0ac020cd" PRIMARY KEY ("rol_id", "funcion_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP CONSTRAINT "PK_8fc8e29994daeffefecf9adcd4e"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD CONSTRAINT "PK_a1d991de75805208749c0407ee5" PRIMARY KEY ("end_point_id")`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_8d632ce50f972ad8f58ea565c7"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP COLUMN "funcion_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD "funcion_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP CONSTRAINT "PK_a1d991de75805208749c0407ee5"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD CONSTRAINT "PK_8fc8e29994daeffefecf9adcd4e" PRIMARY KEY ("end_point_id", "funcion_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_46dc4d18f715459d7bf682d32b" ON "mod_auth"."user_rol" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e959bd66b9f5a8c77de4fd589e" ON "mod_auth"."user_rol" ("rol_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_074ceeadf723390b0fb9f582a5" ON "mod_auth"."user_funcion" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_171ab157447420f1284a8a45d6" ON "mod_auth"."user_funcion" ("funcion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd96b3b407b3a5c35195993c16" ON "mod_auth"."rol_funcion" ("rol_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_273f59cc606dc3d818235f0879" ON "mod_auth"."rol_funcion" ("funcion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d632ce50f972ad8f58ea565c7" ON "mod_auth"."funcion_end_point" ("funcion_id") `);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_237a0fe43278378e9c5729d17af" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD CONSTRAINT "FK_081bb94cc56736d4d76a6e66d98" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."log_history" ADD CONSTRAINT "FK_f063250e076e266042e30653d41" FOREIGN KEY ("user_id") REFERENCES "mod_auth"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "FK_46dc4d18f715459d7bf682d32b9" FOREIGN KEY ("user_id") REFERENCES "mod_auth"."user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "FK_e959bd66b9f5a8c77de4fd589eb" FOREIGN KEY ("rol_id") REFERENCES "mod_auth"."rol"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "FK_074ceeadf723390b0fb9f582a5d" FOREIGN KEY ("user_id") REFERENCES "mod_auth"."user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "FK_171ab157447420f1284a8a45d65" FOREIGN KEY ("funcion_id") REFERENCES "mod_auth"."funcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "FK_dd96b3b407b3a5c35195993c16a" FOREIGN KEY ("rol_id") REFERENCES "mod_auth"."rol"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "FK_273f59cc606dc3d818235f08796" FOREIGN KEY ("funcion_id") REFERENCES "mod_auth"."funcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD CONSTRAINT "FK_8d632ce50f972ad8f58ea565c74" FOREIGN KEY ("funcion_id") REFERENCES "mod_auth"."funcion"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP CONSTRAINT "FK_8d632ce50f972ad8f58ea565c74"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "FK_273f59cc606dc3d818235f08796"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "FK_dd96b3b407b3a5c35195993c16a"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "FK_171ab157447420f1284a8a45d65"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "FK_074ceeadf723390b0fb9f582a5d"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "FK_e959bd66b9f5a8c77de4fd589eb"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "FK_46dc4d18f715459d7bf682d32b9"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."log_history" DROP CONSTRAINT "FK_f063250e076e266042e30653d41"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP CONSTRAINT "FK_081bb94cc56736d4d76a6e66d98"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_237a0fe43278378e9c5729d17af"`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_8d632ce50f972ad8f58ea565c7"`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_273f59cc606dc3d818235f0879"`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_dd96b3b407b3a5c35195993c16"`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_171ab157447420f1284a8a45d6"`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_074ceeadf723390b0fb9f582a5"`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_e959bd66b9f5a8c77de4fd589e"`);
        await queryRunner.query(`DROP INDEX "mod_auth"."IDX_46dc4d18f715459d7bf682d32b"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP CONSTRAINT "PK_8fc8e29994daeffefecf9adcd4e"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD CONSTRAINT "PK_a1d991de75805208749c0407ee5" PRIMARY KEY ("end_point_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP COLUMN "funcion_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD "funcion_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8d632ce50f972ad8f58ea565c7" ON "mod_auth"."funcion_end_point" ("funcion_id") `);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" DROP CONSTRAINT "PK_a1d991de75805208749c0407ee5"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD CONSTRAINT "PK_8fc8e29994daeffefecf9adcd4e" PRIMARY KEY ("funcion_id", "end_point_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_52aa46684e8437845bb0ac020cd"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_dd96b3b407b3a5c35195993c16a" PRIMARY KEY ("rol_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP COLUMN "funcion_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD "funcion_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_273f59cc606dc3d818235f0879" ON "mod_auth"."rol_funcion" ("funcion_id") `);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_dd96b3b407b3a5c35195993c16a"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_52aa46684e8437845bb0ac020cd" PRIMARY KEY ("funcion_id", "rol_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_52aa46684e8437845bb0ac020cd"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_273f59cc606dc3d818235f08796" PRIMARY KEY ("funcion_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP COLUMN "rol_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD "rol_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_dd96b3b407b3a5c35195993c16" ON "mod_auth"."rol_funcion" ("rol_id") `);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" DROP CONSTRAINT "PK_273f59cc606dc3d818235f08796"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "PK_52aa46684e8437845bb0ac020cd" PRIMARY KEY ("rol_id", "funcion_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_fe11cc91f4d6799b60d91973857"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_074ceeadf723390b0fb9f582a5d" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP COLUMN "funcion_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD "funcion_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_171ab157447420f1284a8a45d6" ON "mod_auth"."user_funcion" ("funcion_id") `);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_074ceeadf723390b0fb9f582a5d"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_fe11cc91f4d6799b60d91973857" PRIMARY KEY ("funcion_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_fe11cc91f4d6799b60d91973857"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_171ab157447420f1284a8a45d65" PRIMARY KEY ("funcion_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_074ceeadf723390b0fb9f582a5" ON "mod_auth"."user_funcion" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" DROP CONSTRAINT "PK_171ab157447420f1284a8a45d65"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "PK_fe11cc91f4d6799b60d91973857" PRIMARY KEY ("user_id", "funcion_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_7cf100d94c639983ce7a545526f"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_46dc4d18f715459d7bf682d32b9" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP COLUMN "rol_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD "rol_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_e959bd66b9f5a8c77de4fd589e" ON "mod_auth"."user_rol" ("rol_id") `);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_46dc4d18f715459d7bf682d32b9"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_7cf100d94c639983ce7a545526f" PRIMARY KEY ("rol_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_7cf100d94c639983ce7a545526f"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_e959bd66b9f5a8c77de4fd589eb" PRIMARY KEY ("rol_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_46dc4d18f715459d7bf682d32b" ON "mod_auth"."user_rol" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" DROP CONSTRAINT "PK_e959bd66b9f5a8c77de4fd589eb"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "PK_7cf100d94c639983ce7a545526f" PRIMARY KEY ("user_id", "rol_id")`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."municipio" ALTER COLUMN "centroide" TYPE geometry(GEOMETRY,0)`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."municipio" ALTER COLUMN "geom" TYPE geometry(GEOMETRY,0)`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."provincia" ALTER COLUMN "centroide" TYPE geometry(GEOMETRY,0)`);
        await queryRunner.query(`ALTER TABLE "mod_dpa"."provincia" ALTER COLUMN "geom" TYPE geometry(GEOMETRY,0)`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP CONSTRAINT "UQ_081bb94cc56736d4d76a6e66d98"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP COLUMN "menu_id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD "menu_id" integer`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD CONSTRAINT "REL_081bb94cc56736d4d76a6e66d9" UNIQUE ("menu_id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP CONSTRAINT "PK_048102c1546244e94f6dab37f45"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD CONSTRAINT "PK_048102c1546244e94f6dab37f45" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion_end_point" ADD CONSTRAINT "FK_8d632ce50f972ad8f58ea565c74" FOREIGN KEY ("funcion_id") REFERENCES "mod_auth"."funcion"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "FK_273f59cc606dc3d818235f08796" FOREIGN KEY ("funcion_id") REFERENCES "mod_auth"."funcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "FK_171ab157447420f1284a8a45d65" FOREIGN KEY ("funcion_id") REFERENCES "mod_auth"."funcion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "menu_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "menu_id" integer`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "PK_35b2a8f47d153ff7a41860cceeb"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "PK_35b2a8f47d153ff7a41860cceeb" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_237a0fe43278378e9c5729d17af" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."funcion" ADD CONSTRAINT "FK_081bb94cc56736d4d76a6e66d98" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" DROP CONSTRAINT "PK_c93a22388638fac311781c7f2dd"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol" ADD CONSTRAINT "PK_c93a22388638fac311781c7f2dd" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "FK_e959bd66b9f5a8c77de4fd589eb" FOREIGN KEY ("rol_id") REFERENCES "mod_auth"."rol"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."rol_funcion" ADD CONSTRAINT "FK_dd96b3b407b3a5c35195993c16a" FOREIGN KEY ("rol_id") REFERENCES "mod_auth"."rol"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_rol" ADD CONSTRAINT "FK_46dc4d18f715459d7bf682d32b9" FOREIGN KEY ("user_id") REFERENCES "mod_auth"."user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user_funcion" ADD CONSTRAINT "FK_074ceeadf723390b0fb9f582a5d" FOREIGN KEY ("user_id") REFERENCES "mod_auth"."user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "refreshtokenexp"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "refreshtoken"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP CONSTRAINT "UQ_da5934070b5f2726ebfd3122c80"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" DROP COLUMN "userName"`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "refresh_token_exp" date`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "refresh_token" character varying`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD "user_name" character varying(25) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mod_auth"."user" ADD CONSTRAINT "UQ_d34106f8ec1ebaf66f4f8609dd6" UNIQUE ("user_name")`);
        await queryRunner.query(`DROP TABLE "mod_auth"."log_history"`);
    }

}
